.devcontainer/devcontainer.json
.freeCodeCamp/client/components/error.tsx
.freeCodeCamp/client/components/heading.tsx
.freeCodeCamp/client/index.tsx
.freeCodeCamp/client/styles.css
.freeCodeCamp/client/templates/project.css
.freeCodeCamp/tooling/hot-reload.js
.freeCodeCamp/tooling/server.js
.gitpod.yml
freecodecamp.conf.json
package-lock.json
package.json

Want to take a quick look at this one @ShaunSHamilton - I just ran the install command as you suggested.
Checklist:
Closes #XXXXX

chore: update os

---

.freeCodeCamp/npm/postinstall.js
.freeCodeCamp/tooling/env.js
.freeCodeCamp/tooling/git/build.js
.freeCodeCamp/tooling/git/gitterizer.js
.freeCodeCamp/tooling/hot-reload.js
.freeCodeCamp/tooling/logger.js
.freeCodeCamp/tooling/seed.js
.freeCodeCamp/tooling/server.js
.freeCodeCamp/tooling/test-utils.js
.freeCodeCamp/tooling/test.js
package-lock.json
package.json

Checklist:
Also removes `logover` from root, as it does not appear to be used anywhere there.

chore: update freecodecamp-os to 1.6.2

---

.freeCodeCamp/client/components/block.tsx
.freeCodeCamp/client/components/controls.tsx
.freeCodeCamp/client/styles.css
.freeCodeCamp/client/types/index.ts
.freeCodeCamp/tooling/env.js
.freeCodeCamp/tooling/parser.js
.freeCodeCamp/tooling/server.js
.freeCodeCamp/tooling/test-utils.js
package-lock.json
package.json

chore: update freecodecamp-os to 1.6.4

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/HELP.md
.vscode/settings.json
config/state.json
curriculum/locales/english/learn-how-to-set-up-near-by-building-a-hello-world-smart-contract.md
freecodecamp.conf.json

fix: stuff before beta launch

---

curriculum/locales/english/learn-how-to-set-up-near-by-building-a-hello-world-smart-contract.md

fix: add note about restarting the terminal

---

.vscode/settings.json
build-x-using-y/index.js
config/projects.json
curriculum/locales/english/build-x-using-y.md

feat: add coming soon block

---

.github/ISSUE_TEMPLATE/BUG.md
bash/.bashrc
tooling/camper-info.js

feat: add camper-info script

---

.freeCodeCamp/client/components/controls.tsx
.freeCodeCamp/client/components/error.tsx
.freeCodeCamp/client/components/heading.tsx
.freeCodeCamp/client/styles.css
.freeCodeCamp/client/templates/project.tsx
.freeCodeCamp/client/types/index.ts
.freeCodeCamp/tooling/lesson.js
.freeCodeCamp/tooling/parser.js
.freeCodeCamp/tooling/reset.js
.freeCodeCamp/tooling/seed.js
.freeCodeCamp/tooling/server.js
freecodecamp.conf.json
package-lock.json
package.json
tooling/camper-info.js

chore: update freecodecamp-os to 1.6.5

---

curriculum/locales/english/learn-how-to-set-up-near-by-building-a-hello-world-smart-contract.md

fix: NearBindgen typo

---

Dockerfile

I was getting an error running, so I pinned the packages for now - which fixed it.
Checklist:
Closes #XXXXX

fix: pin near packages

---

.devcontainer/devcontainer.json
.gitpod.yml
freecodecamp.conf.json

feat: update courses extension to 1.7.1

---

package-lock.json
package.json

feat: add babeliser

---

.vscode/settings.json
build-a-sentence-making-smart-contract/jsconfig.json
build-a-sentence-making-smart-contract/package-lock.json
build-a-sentence-making-smart-contract/package.json
build-a-sentence-making-smart-contract/solution.js
config/projects.json
curriculum/locales/english/build-a-sentence-making-smart-contract.md

feat: add first integrated project

---

package.json

fix: pin fccOS and babeliser versions

---

package-lock.json

fix: pin deps better

---

.freeCodeCamp/tooling/reset.js
.freeCodeCamp/tooling/server.js
package-lock.json
package.json

chore: update fcc-os to 1.6.9

---

curriculum/locales/english/learn-how-to-set-up-near-by-building-a-hello-world-smart-contract.md
curriculum/locales/english/learn-near-smart-contracts-by-building-a-word-guessing-game.md

fix: touch up first two projects

---

.freeCodeCamp/client/components/block.tsx
.freeCodeCamp/client/components/checkmark.tsx
.freeCodeCamp/client/index.tsx
.freeCodeCamp/client/styles.css
.freeCodeCamp/client/templates/project.css
.freeCodeCamp/client/types/index.ts
.freeCodeCamp/npm/postinstall.js
.freeCodeCamp/tooling/client-socks.js
.freeCodeCamp/tooling/parser.js
.freeCodeCamp/tooling/server.js
.freeCodeCamp/tooling/test-utils.js
.freeCodeCamp/tooling/test.js
.freeCodeCamp/tooling/validate.js
curriculum/locales/english/learn-near-smart-contracts-by-building-a-word-guessing-game.md
package-lock.json
package.json

chore: update fccOS to 1.7.3

---

.gitignore

Checklist:
Ref #https://github.com/freeCodeCamp/freeCodeCampOS/issues/238

chore: add pattern for testnet files to `.gitignore`

---

.vscode/settings.json
config/projects.json
curriculum/locales/english/learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node.md
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/generate-seed.js
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/jsconfig.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/package-lock.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/package.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/src/word-guess.js
tooling/helpers.js
tooling/rejig.js

feat: add fifth project

---

.vscode/settings.json
build-a-fortune-telling-smart-contract/generate-seed.js
build-a-fortune-telling-smart-contract/get-fortune.js
build-a-fortune-telling-smart-contract/jsconfig.json
build-a-fortune-telling-smart-contract/package-lock.json
build-a-fortune-telling-smart-contract/package.json
config/projects.json
curriculum/locales/english/build-a-fortune-telling-smart-contract.md
curriculum/locales/english/learn-near-accounts-by-creating-a-named-testnet-account.md

feat: add sixth project

---

.vscode/settings.json
build-a-fortune-telling-smart-contract/generate-seed.js
build-a-fortune-telling-smart-contract/get-fortune.js
build-a-fortune-telling-smart-contract/jsconfig.json
build-a-fortune-telling-smart-contract/package-lock.json
build-a-fortune-telling-smart-contract/package.json
config/projects.json
curriculum/locales/english/build-a-fortune-telling-smart-contract.md
curriculum/locales/english/learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node.md
curriculum/locales/english/learn-near-accounts-by-creating-a-named-testnet-account.md
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/generate-seed.js
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/jsconfig.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/package-lock.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/package.json
learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node/src/word-guess.js
learn-near-accounts-by-creating-a-named-testnet-account/jsconfig.json
learn-near-accounts-by-creating-a-named-testnet-account/package-lock.json
learn-near-accounts-by-creating-a-named-testnet-account/package.json
learn-near-accounts-by-creating-a-named-testnet-account/src/word-guess.js
tooling/helpers.js
tooling/rejig.js

feat(next): add second group of projects

---

curriculum/locales/english/learn-how-to-interact-with-near-programs-using-the-near-javascript-api-and-node.md

fix: contract typo

---

curriculum/locales/english/build-a-sentence-making-smart-contract.md

Checklist:
Fixes small typos in the first integrated project.

fix: typos in the first integrated project

---

.vscode/settings.json

fix: default to bash
